name: formazione_bwapps
description: Your weather, whenever you wish
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  dio: ^5.1.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  form_field_validator: ^1.1.0
  freezed_annotation: ^2.2.0
  go_router: ^6.5.3
  hooks_riverpod: ^2.3.4
  json_annotation: ^4.8.0
  riverpod_annotation: ^2.1.1

dev_dependencies:
  build_runner: ^2.3.3
  go_router_builder: ^1.2.1
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.2.1

  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
